### ISSUE TITLE
Awkward Error

### ISSUE THREAD

**Issue by iiNFiNiTYx** [Tim-R/SignEdit#2]
So I have been using SignEdit since about 1.6 and it hasn't caused me issues, other than if I needed a dependency or some other plugin caused the error, but today It was working fine, then I stopped the server to add more plugins. These are the same plugins as I used (Long story short: my HDD/hard-drive reset 3 times, I'm on my 3rd starting my server from scratch with same plugins as I had before) in 1.6. I currently (about 10 mins ago) updated to 1.7.2 CB to see if it would fix the issue. But no, still erroring. It says "v3.3.2 is the current/latest version" and my error says "Out of date?," and I do not understand this at all. Please help :smiley:!

[16:36:58] [Server thread/ERROR]: Error occurred while enabling SignEdit v3.3.2 (Is it up to date?)
java.lang.InstantiationError: org.mcstats.Metrics
    at net.timroden.signedit.SignEdit.onEnable(SignEdit.java:47) ~[?:?]
    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:217) ~[craftbukkit.jar:git-Bukkit-1.6.4-R2.0-37-g4857595-b2951jnks]
    at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:457) [craftbukkit.jar:git-Bukkit-1.6.4-R2.0-37-g4857595-b2951jnks]
    at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:381) [craftbukkit.jar:git-Bukkit-1.6.4-R2.0-37-g4857595-b2951jnks]
    at org.bukkit.craftbukkit.v1_7_R1.CraftServer.loadPlugin(CraftServer.java:298) [craftbukkit.jar:git-Bukkit-1.6.4-R2.0-37-g4857595-b2951jnks]
    at org.bukkit.craftbukkit.v1_7_R1.CraftServer.enablePlugins(CraftServer.java:280) [craftbukkit.jar:git-Bukkit-1.6.4-R2.0-37-g4857595-b2951jnks]
    at net.minecraft.server.v1_7_R1.MinecraftServer.m(MinecraftServer.java:338) [craftbukkit.jar:git-Bukkit-1.6.4-R2.0-37-g4857595-b2951jnks]
    at net.minecraft.server.v1_7_R1.MinecraftServer.g(MinecraftServer.java:315) [craftbukkit.jar:git-Bukkit-1.6.4-R2.0-37-g4857595-b2951jnks]
    at net.minecraft.server.v1_7_R1.MinecraftServer.a(MinecraftServer.java:275) [craftbukkit.jar:git-Bukkit-1.6.4-R2.0-37-g4857595-b2951jnks]
    at net.minecraft.server.v1_7_R1.DedicatedServer.init(DedicatedServer.java:175) [craftbukkit.jar:git-Bukkit-1.6.4-R2.0-37-g4857595-b2951jnks]
    at net.minecraft.server.v1_7_R1.MinecraftServer.run(MinecraftServer.java:420) [craftbukkit.jar:git-Bukkit-1.6.4-R2.0-37-g4857595-b2951jnks]
    at net.minecraft.server.v1_7_R1.ThreadServerApplication.run(SourceFile:617) [craftbukkit.jar:git-Bukkit-1.6.4-R2.0-37-g4857595-b2951jnks]

Yes I see it says "...Metrics..." but I have had the plugin metrics before and it still did the same thing.

**Comment by Tim-R** [comment]
The issue was caused by an outdated Metrics class. Now that it's updated, the plugin should work just fine.
